package com.jzh.wanandroid.data.db.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jzh.wanandroid.data.db.model.LoginDbData;

import com.jzh.wanandroid.data.db.model.LoginDbDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginDbDataDaoConfig;

    private final LoginDbDataDao loginDbDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginDbDataDaoConfig = daoConfigMap.get(LoginDbDataDao.class).clone();
        loginDbDataDaoConfig.initIdentityScope(type);

        loginDbDataDao = new LoginDbDataDao(loginDbDataDaoConfig, this);

        registerDao(LoginDbData.class, loginDbDataDao);
    }
    
    public void clear() {
        loginDbDataDaoConfig.clearIdentityScope();
    }

    public LoginDbDataDao getLoginDbDataDao() {
        return loginDbDataDao;
    }

}
