package com.jzh.wanandroid.data.db.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jzh.wanandroid.data.db.model.ProjectTypeResponseData;

import com.jzh.wanandroid.data.db.model.ProjectTypeResponseDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectTypeResponseDataDaoConfig;

    private final ProjectTypeResponseDataDao projectTypeResponseDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectTypeResponseDataDaoConfig = daoConfigMap.get(ProjectTypeResponseDataDao.class).clone();
        projectTypeResponseDataDaoConfig.initIdentityScope(type);

        projectTypeResponseDataDao = new ProjectTypeResponseDataDao(projectTypeResponseDataDaoConfig, this);

        registerDao(ProjectTypeResponseData.class, projectTypeResponseDataDao);
    }
    
    public void clear() {
        projectTypeResponseDataDaoConfig.clearIdentityScope();
    }

    public ProjectTypeResponseDataDao getProjectTypeResponseDataDao() {
        return projectTypeResponseDataDao;
    }

}
